# Generated by Django 4.1.2 on 2022-11-15 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivateChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_room_name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Room name"
                    ),
                ),
                (
                    "addition_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time of addition"
                    ),
                ),
                (
                    "user1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Chat owner",
                    ),
                ),
                (
                    "user2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Chat opponent",
                    ),
                ),
            ],
            options={
                "verbose_name": "private chat",
                "verbose_name_plural": "private chats",
                "db_table": "private_chats",
                "ordering": ["addition_time"],
            },
        ),
        migrations.CreateModel(
            name="PublicChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_room_name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Room name"
                    ),
                ),
                (
                    "addition_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time of addition"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_owner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner of chat room",
                    ),
                ),
                (
                    "participant",
                    models.ManyToManyField(
                        related_name="room_participant",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Participant of chat room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat room",
                "verbose_name_plural": "Chat rooms",
                "db_table": "public_chats",
                "ordering": ["addition_time"],
            },
        ),
        migrations.CreateModel(
            name="PublicChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Message")),
                ("send_time", models.DateTimeField(auto_now_add=True)),
                (
                    "room_chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.publicchat",
                        verbose_name="Chat room",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sender",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat room message",
                "verbose_name_plural": "Chat room messages",
                "db_table": "public_chats_messages",
                "ordering": ["send_time"],
            },
        ),
        migrations.CreateModel(
            name="PrivateChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Message")),
                ("send_time", models.DateTimeField(auto_now_add=True)),
                (
                    "room_chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.privatechat",
                        verbose_name="Private chat",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sender",
                    ),
                ),
            ],
            options={
                "verbose_name": "Private chat message",
                "verbose_name_plural": "Private chat messages",
                "db_table": "private_chat_messages",
                "ordering": ["send_time"],
            },
        ),
    ]
