# Generated by Django 4.1.2 on 2022-10-08 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_room_name', models.CharField(max_length=20, verbose_name='Room name')),
                ('addition_time', models.DateTimeField(auto_now_add=True, verbose_name='Time of addition')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'chat rooms',
                'verbose_name_plural': 'chat room',
                'db_table': 'chat_rooms',
                'ordering': ['addition_time'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Message')),
                ('send_time', models.DateTimeField(auto_now_add=True)),
                ('room_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroommodel', verbose_name='Chat room')),
                ('sener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'messages',
                'verbose_name_plural': 'message',
                'db_table': 'chat_room_messages',
                'ordering': ['send_time'],
            },
        ),
    ]
